/**
 * Visitor-facing booking UI text (Japanese). Setup names, questions and
 * messages come from the definition; these are the UI's own words.
 */

const minutesText = (minutes: number): string => {
  if (minutes % 1440 === 0) return `${minutes / 1440}日`;
  if (minutes % 60 === 0) return `${minutes / 60}時間`;
  if (minutes > 60) return `${Math.floor(minutes / 60)}時間${minutes % 60}分`;
  return `${minutes}分`;
};

export const UI = {
  loading: '予約画面を読み込んでいます…',
  unavailable: 'この予約ページは現在ご利用いただけません。',
  loadFailed: '予約画面を読み込めませんでした。通信状況をご確認のうえ、もう一度お試しください。',
  unsupported: 'この予約ページは現在表示できません。お手数ですが、時間をおいて再度お試しください。',
  retry: '再読み込み',
  steps: ['日付', '時間', 'お客様情報', '確認', '完了'] as const,
  /** The step indicator label of every step (the time-slot flow uses the last five). */
  stepLabels: { service: 'メニュー', party: '人数', date: '日付', time: '時間', details: 'お客様情報', review: '確認', outcome: '完了' } as const,
  stepsLabel: '予約の手順',
  // Service flow.
  serviceHeading: 'ご希望のメニューを選択してください',
  serviceLegend: 'メニュー',
  variantLegend: 'メニューの種類',
  practitionerLabel: '担当者のご希望',
  anyPractitioner: '指定しない',
  anyPractitionerNote: '「指定しない」を選ぶと、ご希望の日時に対応できる担当者をこちらで決めます。',
  durationRange: (min: string, max: string) => `所要時間：${min}〜${max}（種類により異なります）`,
  chooseService: 'メニューを選択してください。',
  chooseVariant: 'メニューの種類を選択してください。',
  chooseServiceFirst: '先にメニューを選択してください。',
  backToService: 'メニューを選び直す',
  reviewService: 'メニュー',
  reviewPractitioner: '担当者',
  reviewAnyPractitioner: '指定なし（担当者はこちらで決めます）',
  // Party flow.
  partyHeading: 'ご来店の人数を選択してください',
  partyLabel: '人数',
  partyPrompt: '選択してください',
  partyOption: (size: number) => `${size}名`,
  partyRange: (min: number, max: number) => `${min}〜${max}名様までご予約いただけます。`,
  partyInvalid: (min: number, max: number) => `人数は${min}〜${max}の整数（半角数字）で入力してください。`,
  choosePartyFirst: '先に人数を選択してください。',
  backToParty: '人数を選び直す',
  diningDuration: (minutes: number) => `ご利用時間：${minutesText(minutes)}`,
  reviewParty: '人数',
  reviewDiningDuration: 'ご利用時間',
  toDates: '日付の選択へ進む',
  // A selection the server did not accept (validation_failed + invalid_selection).
  invalidSelection: {
    service: '選択したメニューではご予約いただけませんでした。お手数ですが、メニューを選び直してください。',
    party: 'ご指定の人数ではご予約いただけませんでした。お手数ですが、人数を選び直してください。',
    date: '選択した方法・場所または担当者ではご予約いただけませんでした。お手数ですが、選び直してください。',
  } as Record<string, string>,
  dateHeading: 'ご希望の日付を選択してください',
  timeHeading: (date: string) => `${date}の空き時間`,
  detailsHeading: 'お客様情報の入力',
  reviewHeading: '予約内容の確認',
  duration: (minutes: number) => `所要時間：${minutesText(minutes)}`,
  minutes: minutesText,
  locationLegend: 'ご希望の方法・場所',
  hostLabel: '担当者',
  anyHost: '指定しない',
  timeZoneLabel: '時刻の表示',
  timeZoneNote: (venue: string) => `予約はすべて${venue}で管理されます。表示を切り替えても予約される日時は変わりません。`,
  timesShownIn: (zone: string) => `時刻は${zone}で表示しています。`,
  previousWeeks: '前の期間',
  nextWeeks: '次の期間',
  datesLabel: '日付',
  available: '空きあり',
  full: '空きなし',
  loadingAvailability: '空き状況を確認しています…',
  availabilityFailed: '空き状況を読み込めませんでした。',
  reloadAvailability: '空き状況を再読み込み',
  noDatesInRange: 'この期間に予約できる日がありません。別の期間をお選びください。',
  noSlots: 'この日に予約できる時間はありません。別の日付をお選びください。',
  chooseLocationFirst: '先にご希望の方法・場所を選択してください。',
  backToDates: '日付を選び直す',
  holding: '選択した時間を確保しています…',
  holdCountdown: (time: string) => `選択した時間を確保しています（残り ${time}）。時間内に予約を完了してください。`,
  holdExpired: '確保していた時間の有効期限が切れました。お手数ですが、時間を選び直してください。',
  backToTimes: '時間を選び直す',
  toReview: '確認へ進む',
  back: '修正する',
  submitAutomatic: '予約を確定する',
  submitManual: '予約をリクエストする',
  sending: '送信中…',
  reviewDateTime: '日時',
  reviewVenueTime: (time: string) => `（${time}）`,
  reviewDuration: '所要時間',
  reviewLocation: '方法・場所',
  reviewHost: '担当者',
  policyAutomatic: '送信すると予約が確定します。',
  policyManual: (window: string | null) =>
    `この予約は担当者の承認後に確定します。送信した時点ではまだ確定していません。${window ? `承認の結果は、お申し込みから${window}以内を目安にお知らせします。` : ''}`,
  cutoffBoth: '開始時刻が近いため、この予約はオンラインでの変更・キャンセルができません。変更・キャンセルが必要な場合は直接お問い合わせください。',
  cutoffCancel: '開始時刻が近いため、この予約はオンラインでのキャンセルができません。キャンセルが必要な場合は直接お問い合わせください。',
  cutoffReschedule: '開始時刻が近いため、この予約はオンラインでの日時変更ができません。変更が必要な場合は直接お問い合わせください。',
  confirmedHeading: '予約が確定しました',
  pendingHeading: '予約リクエストを受け付けました（まだ確定していません）',
  confirmingHeading: '予約を受け付けました（確定の処理中です）',
  rejectedHeading: '予約は確定しませんでした',
  expiredHeading: '承認期限までに確定しなかったため、予約は成立しませんでした',
  cancelledHeading: 'この予約はキャンセルされました',
  pendingDeadline: (deadline: string) => `${deadline}までに、予約を確定できるかどうかをお知らせします。それまでは予約は確定していません。`,
  confirmingNote: '確定の処理が終わるまで、このままお待ちください。',
  defaultConfirmedMessage: 'ご予約ありがとうございます。確認のメールをお送りしました。',
  defaultPendingMessage: 'ご予約のリクエストを受け付けました。担当者が確認のうえ、結果をメールでお知らせします。',
  manageLink: '予約の確認・変更・キャンセル',
  manageNote: 'このリンクはメールでもお送りします。ご本人専用のリンクですので、他の方には共有せず大切に保管してください。',
  redirecting: '完了ページへ移動しています…',
  previewMarker: 'プレビュー：サンプルの空き状況です（実際の予約はできません）',
  previewSource: (source: string) => `${source} の内容を表示しています。担当者名と空き状況はすべて架空のサンプルで、送信内容はどこにも送られません。`,
  previewLog: '最後の送信内容（送信されていません）',
  previewSensitive: '（要配慮情報のため表示しません）',
  previewNothing: 'まだ送信されていません。',
  previewRedirect: (path: string) => `本番では、完了後に ${path} へ移動します（プレビューでは移動しません）。`,
  verificationPending: '送信前の確認が完了していません。確認が終わるまでお待ちください。',
  verificationUnavailable: '送信前の確認を読み込めませんでした。ページを再読み込みしてから、もう一度お試しください。',
  verificationLabel: '送信前の確認',
  networkError: '通信に失敗しました。入力内容は保持されています。接続をご確認のうえ、もう一度お試しください。',
  retryAfter: (seconds: number) => `約${seconds}秒後に、もう一度お試しください。`,
  honeypotLabel: 'この欄は入力しないでください',
  errorSummary: '入力内容に誤りがあります。以下の項目をご確認ください。',
  empty: '（未入力）',
};
