/**
 * The zod schemas `yatris schema sync` derives from a manifest's canonical
 * schema (YatrisCMS#307): one `z.object` per Content Type, for the `schema`
 * option of `getYatrisList`, `getYatrisSingleton` and `getYatrisItem`. The
 * output depends on the canonical snapshot alone, so the same revision always
 * yields the same file, which the lock then pins like Yatris's own files.
 */

export const ZOD_PATH = 'src/generated/yatris-zod.ts';

interface CanonicalField {
  key: string;
  type: string;
  required?: boolean;
  validations?: { allowed_values?: unknown; min_items?: unknown; max_items?: unknown };
  fields?: CanonicalField[];
}

interface CanonicalType {
  slug: string;
  structure: string;
  schema_version: number;
  fields: CanonicalField[];
}

/** The zod module for a manifest's canonical schema. */
export function generateZodModule(canonical: string, schemaRevision: string): string {
  const types = contentTypes(canonical);
  const lines = [
    `// Generated by @yatris/astro from schema revision ${schemaRevision}. Do not edit.`,
    '// Update it with: npx yatris schema sync --manifest <manifest from the Yatris MCP>',
    "import { z } from 'astro/zod';",
    '',
    `export const schemaRevision = ${literal(schemaRevision)} as const;`,
    '',
    '/** An image chosen from the Yatris media library (a legacy URL string on old content). */',
    'export const yatrisImage = z.union([',
    '  z.object({ asset_id: z.number().nullable(), url: z.string(), webp_url: z.string().nullable(), alt: z.string(), width: z.number(), height: z.number(), mime: z.string() }),',
    '  z.string(),',
    ']);',
    '',
    '/** A file from the Yatris media library (a legacy URL string on old content). */',
    'export const yatrisFile = z.union([z.object({ url: z.string(), mime: z.string() }), z.string()]);',
    '',
    '/** Another content item, as the Delivery API expands a reference. */',
    'export const yatrisReference = z.object({ id: z.number(), canonical_id: z.string(), title: z.string() });',
  ];

  const names: string[] = [];
  const taken = new Set<string>();
  for (const type of types) {
    // Two slugs can share an identifier (`a-b`, `a_b`): number the later one
    let name = `${identifier(type.slug)}Schema`;
    for (let n = 2; taken.has(name); n++) name = `${identifier(type.slug)}Schema${n}`;
    taken.add(name);
    names.push(`  ${literal(type.slug)}: ${name},`);
    lines.push('', `/** Content Type "${type.slug}" (${type.structure}, schema v${type.schema_version}). */`, `export const ${name} = ${objectOf(type.fields, '')};`);
  }

  lines.push('', '/** Every Content Type of this Website, by slug. */', 'export const yatrisSchemas = {', ...names, '} as const;');

  return `${lines.join('\n')}\n`;
}

function contentTypes(canonical: string): CanonicalType[] {
  const parsed = JSON.parse(canonical) as { content_types?: unknown };
  const types = Array.isArray(parsed.content_types) ? (parsed.content_types as CanonicalType[]) : [];
  return types.filter((type) => typeof type?.slug === 'string');
}

/** A `z.object` of fields; `indent` lines up nested members. */
function objectOf(fields: CanonicalField[] | undefined, indent: string): string {
  const members = (fields ?? []).filter((field) => typeof field?.key === 'string');
  if (members.length === 0) return 'z.object({})';
  const inner = `${indent}  `;
  const lines = members.map((field) => `${inner}${literal(field.key)}: ${fieldSchema(field, inner)},`);
  return `z.object({\n${lines.join('\n')}\n${indent}})`;
}

function fieldSchema(field: CanonicalField, indent: string): string {
  const base = valueSchema(field, indent);
  return field.required ? base : `${base}.nullish()`;
}

function valueSchema(field: CanonicalField, indent: string): string {
  const values = field.validations?.allowed_values;
  const allowed = Array.isArray(values) ? values.filter((v): v is string => typeof v === 'string') : [];
  const choice = allowed.length > 0 ? `z.enum([${allowed.map(literal).join(', ')}])` : 'z.string()';

  switch (field.type) {
    case 'number':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'select':
      return choice;
    case 'multi_select':
      return `z.array(${choice})`;
    case 'image':
      return 'yatrisImage';
    case 'multi_image':
      return 'z.array(yatrisImage)';
    case 'file':
      return 'yatrisFile';
    case 'reference':
      return 'yatrisReference';
    case 'multi_reference':
      return 'z.array(yatrisReference)';
    case 'object':
      return 'z.record(z.string(), z.unknown())';
    case 'blocks':
      return 'z.array(z.record(z.string(), z.unknown()))';
    case 'repeater':
      return repeaterSchema(field, indent);
    case 'text':
    case 'textarea':
    case 'rich_text':
    case 'date':
    case 'datetime':
      return 'z.string()';
    default:
      return 'z.unknown()';
  }
}

/**
 * A repeater (YatrisCMS#307): a list of objects of its sub-fields, with its
 * item bounds. An optional repeater may also be empty, as Yatris allows.
 */
function repeaterSchema(field: CanonicalField, indent: string): string {
  const min = wholeNumber(field.validations?.min_items);
  const max = wholeNumber(field.validations?.max_items);
  let list = `z.array(${objectOf(field.fields, indent)})`;

  if (max !== null) list += `.max(${max})`;
  if (min !== null && min > 0) {
    list += field.required
      ? `.min(${min})`
      : `.refine((items) => items.length === 0 || items.length >= ${min}, { message: ${literal(`must contain at least ${min} items`)} })`;
  }
  return list;
}

function wholeNumber(value: unknown): number | null {
  return typeof value === 'number' && Number.isInteger(value) && value >= 0 ? value : null;
}

/** A camelCase identifier for a slug, never starting with a digit. */
function identifier(slug: string): string {
  const words = slug.split(/[^A-Za-z0-9]+/).filter((word) => word !== '');
  const name = words.map((word, index) => (index === 0 ? word.charAt(0).toLowerCase() : word.charAt(0).toUpperCase()) + word.slice(1)).join('');
  return /^[A-Za-z]/.test(name) ? name : `type${name.charAt(0).toUpperCase()}${name.slice(1)}`;
}

function literal(value: string): string {
  return JSON.stringify(value);
}
